version: '3'

services:

  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672

  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    volumes:
      - ./mnesia1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=123123
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  rabbitmq2:
    build: .
    links:
      - rabbitmq1
    hostname: rabbitmq2
    volumes:
      - ./mnesia2:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=123123
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  rabbitmq3:
    build: .
    links:
      - rabbitmq1
    hostname: rabbitmq3
    volumes:
      - ./mnesia3:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=123123
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin